mkdir %1\source
xcopy source\*.cpp %1\source /c /y
xcopy source\*.hpp %1\source /c /y
xcopy source\*.h %1\source /c /y
xcopy source\*.ds* %1\source /c /y
xcopy source\Makefile.* %1\source /c /y
xcopy source\aclocal.m4 %1\source /c /y
xcopy source\AUTHORS %1\source /c /y
xcopy source\README %1\source /c /y
xcopy source\autogen.sh %1\source /c /y
xcopy source\*.txt %1\source /c /y
xcopy source\configure.* %1\source /c /y
xcopy source\COPYING %1\source /c /y
xcopy source\depcomp*.* %1\source /c /y
xcopy source\INSTALL*.* %1\source /c /y
xcopy source\missing %1\source /c /y
xcopy source\mkinstalldirs %1\source /c /y
xcopy source\NEWS %1\source /c /y
xcopy source\README*.* %1\source /c /y
xcopy source\*.dox %1\source /c /y
xcopy source\*.ico %1\source /c /y
xcopy source\*.rc %1\source /c /y
