#ifndef __UOX3_ENUMS__
#define __UOX3_ENUMS__

enum UnicodeTypes
{
	ZERO = 0,
	ENU,
	CHT,
	FRA,
	KOR,
	DEU,
	POR,
	ITA,
	RUS,
	SPA,
	TOTAL_LANGUAGES
};

enum SpeechType
{
	UNKNOWN = -1,
	TALK = 0,				// normal system message
	PROMPT = 1,				// Display as system prompt
	EMOTE = 2,				// : text
	SAY = 3,				// character speaking
	OBJ = 4,				// at object
	NOTHING = 5,			// does not display
	SYSTEM = 6,				// text labelling an item
	NOSCROLL = 7,			// status msg, does not scroll
	WHISPER = 8,			// only those close can here
	YELL = 9,				// can be heard 2 screens away
	BROADCAST = 0xFF,
};

enum FontType
{
	FNT_BOLD = 0,
	FNT_TEXT_WITH_SHADOW,
	FNT_BOLD_PLUS_SHADOW,
	FNT_NORMAL,
	FNT_GOTHIC,
	FNT_ITALIC,
	FNT_SMALL_DARK,
	FNT_COLOURFUL,
	FNT_RUNIC,		// Only use CAPS!
	FNT_SMALL_LIGHT,
	FNT_UNKNOWN
};

enum SpeechTarget
{
	SPTRG_INDIVIDUAL = 0,		// aimed at individual person
	SPTRG_PCS,					// all PCs in range
	SPTRG_PCNPC,				// all NPCs and PCs in range
	SPTRG_BROADCASTPC,				// ALL PCs everywhere + NPCs in range
	SPTRG_BROADCASTALL
};

enum SpeakerType
{
	SPK_SYSTEM = 0,
	SPK_CHARACTER,
	SPK_ITEM,
	SPK_UNKNOWN
};

enum GuildType
{
	GT_STANDARD = 0,
	GT_ORDER,
	GT_CHAOS,
	GT_UNKNOWN,
	GT_COUNT
};

enum GuildRelation
{
	GR_NEUTRAL = 0,
	GR_WAR,
	GR_ALLY,
	GR_UNKNOWN,
	GR_SAME,
	GR_COUNT
};

enum PickupLocations
{
	PL_NOWHERE = 0,
	PL_GROUND,
	PL_OWNPACK,
	PL_OTHERPACK,
	PL_PAPERDOLL
};

enum WeatherType
{
	LIGHT = 0,
	RAIN,
	COLD,
	HEAT,
	LIGHTNING,
	SNOW,
	WEATHNUM
};

enum WorldType
{
	WRLD_SPRING = 0,
	WRLD_SUMMER,
	WRLD_AUTUMN,
	WRLD_WINTER,
	WRLD_DESOLATION,
	WRLD_UNKNOWN,
	WRLD_COUNT
};

// EXIT CODES
enum ErrorCodes
{
	UNKNOWN_ERROR = 666,
	FATAL_UOX3_JAVASCRIPT = 50,
	FATAL_UOX3_ALLOC_WORLDSTATE = 100,
	FATAL_UOX3_ALLOC_MAPREGIONS,
	FATAL_UOX3_ALLOC_ADMIN,
	FATAL_UOX3_ALLOC_BOATS,
	FATAL_UOX3_ALLOC_COMBAT,
	FATAL_UOX3_ALLOC_COMMANDS,
	FATAL_UOX3_ALLOC_GUILDS,
	FATAL_UOX3_ALLOC_GUMPS,
	FATAL_UOX3_ALLOC_ITEMS,
	FATAL_UOX3_ALLOC_MAP,
	FATAL_UOX3_ALLOC_NPCS,
	FATAL_UOX3_ALLOC_SKILLS,
	FATAL_UOX3_ALLOC_TOWNS,
	FATAL_UOX3_ALLOC_WEIGHT,
	FATAL_UOX3_ALLOC_TARG,
	FATAL_UOX3_ALLOC_NETWORK,
	FATAL_UOX3_ALLOC_MAGIC,
	FATAL_UOX3_ALLOC_RACES,
	FATAL_UOX3_ALLOC_SHOP,
	FATAL_UOX3_ALLOC_WEATHER,
	FATAL_UOX3_ALLOC_MOVE,
	FATAL_UOX3_ALLOC_EFFECTS,
	FATAL_UOX3_ALLOC_WHOLIST,
	FATAL_UOX3_ALLOC_DICTIONARY,
	FATAL_UOX3_ALLOC_BOOKS,
	FATAL_UOX3_ALLOC_PAGEVECTOR,
	FATAL_UOX3_ALLOC_ACCOUNTS,
	FATAL_UOX3_ALLOC_MAPREGION,
	FATAL_UOX3_ALLOC_TRIGGERS,
	FATAL_UOX3_ALLOC_SPEECH,
	FATAL_UOX3_ALLOC_SCRIPTS,

	FATAL_UOX3_CHARS = 150,
	FATAL_UOX3_TEFFECTS,

	FATAL_UOX3_ITEMS = 200,
	FATAL_UOX3_LOSCACHE,
	FATAL_UOX3_ITEMIDS,

	FATAL_UOX3_CREATE_UOXMENUS = 250,

	FATAL_UOX3_ALLOC_ITEMSP = 300,
	FATAL_UOX3_ALLOC_CHARSP,
	FATAL_UOX3_ALLOC_SPAWNSP,
	FATAL_UOX3_ALLOC_CSPAWNSP,
	FATAL_UOX3_ALLOC_GLOWSP,


	FATAL_UOX3_MAP_NOT_FOUND = 350,
	FATAL_UOX3_STATICS_INDEX_NOT_FOUND,
	FATAL_UOX3_STATICS_NOT_FOUND,
	FATAL_UOX3_VERSION_NOT_FOUND,
	FATAL_UOX3_TILEDATA_NOT_FOUND,
	FATAL_UOX3_MULTI_DATA_NOT_FOUND,
	FATAL_UOX3_MULTI_INDEX_NOT_FOUND,
};

// List of skill numbers (For later implementation)
enum Skills
{
	ALCHEMY = 0,
	ANATOMY,
	ANIMALLORE,
	ITEMID,
	ARMSLORE,
	PARRYING,
	BEGGING,
	BLACKSMITHING,
	BOWCRAFT,
	PEACEMAKING,
	CAMPING,
	CARPENTRY,
	CARTOGRAPHY,
	COOKING ,
	DETECTINGHIDDEN ,
	ENTICEMENT ,
	EVALUATINGINTEL ,
	HEALING ,
	FISHING ,
	FORENSICS ,
	HERDING ,
	HIDING ,
	PROVOCATION ,
	INSCRIPTION ,
	LOCKPICKING ,
	MAGERY ,
	MAGICRESISTANCE ,
	TACTICS ,
	SNOOPING ,
	MUSICIANSHIP ,
	POISONING ,
	ARCHERY ,
	SPIRITSPEAK ,
	STEALING ,
	TAILORING ,
	TAMING ,
	TASTEID ,
	TINKERING ,
	TRACKING ,
	VETERINARY ,
	SWORDSMANSHIP ,
	MACEFIGHTING ,
	FENCING ,
	WRESTLING ,
	LUMBERJACKING ,
	MINING ,

	MEDITATION  ,
	STEALTH  ,
	REMOVETRAPS ,  // lb, have to be extacly the numbers the client sends !!


	ALLSKILLS , // #skills+1

	STRENGTH , // #skills+2
	DEXTERITY , // #skills+3
	INTELLECT , // #skills+4
	FAME , // #skills+5
	KARMA,  // #skills+6 
	SKILLS     // #skills+7
};

enum __TIMERID__ 
{
	TIMER_ERROR = -1,
	CORPSE_DECAY = 0,
	LOOT_DECAY,
	WEATHER,
	SHOP_SPAWN,
	DECAY,
	INVISIBILITY,
	OBJECT_USAGE,
	GATE,
	POISON,
	LOGIN_TIMEOUT,
	HITPOINT_REGEN,
	STAMINA_REGEN,
	MANA_REGEN,
	ARMORAFFECTMANA_REGEN,
	BASE_FISHING,
	RANDOM_FISHING,
	SPIRIT_SPEAK,
	BEGGING_T,
	PLAYER_CORPSE
};

enum ObjectType
{
	OT_CBO = 0,
	OT_CHAR,
	OT_ITEM,
	OT_MULTI
};

#endif