import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPECS = ROOT / "source" / "UOXJSPropertySpecs.h"
ENUMS = ROOT / "source" / "UOXJSPropertyEnums.h"
OUTPUT = ROOT / "source" / "UOXJSPropertyAdapters.cpp"

FAMILIES = {
    "CSpell": "CSpellProps",
    "CGlobalSkill": "CGlobalSkillProps",
    "CCreateEntry": "CCreateEntryProps",
    "CTimer": "CTimerProps",
    "CRace": "CRaceProps",
    "CRegion": "CRegionProps",
    "CSpawnRegion": "CSpawnRegionProps",
    "CGuild": "CGuildProps",
    "CCharacter": "CCharacterProps",
    "CItem": "CItemProps",
    "CSocket": "CSocketProps",
    "CSkills": "CSkillsProps",
    "CGumpData": "CGumpDataProps",
    "CAccount": "CAccountProps",
    "CConsole": "CConsoleProps",
    "CScriptSection": "CScriptSectionProps",
    "CResource": "CResourceProps",
    "CParty": "CPartyProps",
    "CScript": "CScriptProps",
}

INTEGER_ENUMS = {
    "CSpell": "CSpell_Properties",
    "CGlobalSkill": "CGlobalSkill_Properties",
    "CCreateEntry": "CCreateEntry_Properties",
    "CTimer": "CTimer_Properties",
    "CGumpData": "CGumpData_Properties",
}

ENUM_PREFIXES = {
    "CSpell": "CSP",
    "CGlobalSkill": "CGSKILL",
    "CCreateEntry": "CMAKE",
    "CTimer": "TIMER",
    "CGumpData": "CGumpData",
}


def normalized(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def enum_values(text, enum_name):
    match = re.search(rf"enum\s+{enum_name}\s*\{{(.*?)\}};", text, re.S)
    if not match:
        raise RuntimeError(f"Missing enum {enum_name}")
    result = {}
    value = -1
    for entry in match.group(1).split(","):
        entry = re.sub(r"//.*", "", entry).strip()
        if not entry:
            continue
        token, _, explicit = entry.partition("=")
        token = token.strip()
        value = int(explicit.strip(), 0) if explicit else value + 1
        result[normalized(token)] = value
    return result


def main():
    specs = SPECS.read_text(encoding="utf-8")
    enums = ENUMS.read_text(encoding="utf-8")
    table_text = specs[specs.index("// Property table") :]
    properties = re.findall(r"UX_PSG(S?)\(\s*(\w+)\s*,\s*(\w+)\s*,", table_text)

    enum_maps = {
        main_name: enum_values(enums, enum_name)
        for main_name, enum_name in INTEGER_ENUMS.items()
    }
    skill_ids = {
        normalized(attr): index
        for index, (_, main_name, attr) in enumerate(
            prop for prop in properties if prop[1] == "CSkills"
        )
    }

    lines = [
        "// Generated by tools/generate_mozjs_property_adapters.py.",
        '#include "uox3.h"',
        '#include "UOXJSPropertyFuncs.h"',
        "",
        "using LegacyGetter = bool (*)( JSContext *, JSObject *, jsid, JS::Value * );",
        "using LegacySetter = bool (*)( JSContext *, JSObject *, jsid, bool, JS::Value * );",
        "",
        "static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, const char *name )",
        "{",
        "\tauto args = JS::CallArgsFromVp( argc, vp );",
        "\tJS::RootedObject obj( cx );",
        "\tif( !args.computeThis( cx, &obj )) return false;",
        "\tJS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));",
        "\tif( !property ) return false;",
        "\tJS::RootedId id( cx );",
        "\tif( !JS_StringToId( cx, property, &id )) return false;",
        "\treturn getter( cx, obj, id, args.rval().address() );",
        "}",
        "",
        "static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, int32_t propertyId )",
        "{",
        "\tauto args = JS::CallArgsFromVp( argc, vp );",
        "\tJS::RootedObject obj( cx );",
        "\tif( !args.computeThis( cx, &obj )) return false;",
        "\treturn getter( cx, obj, JS::PropertyKey::Int( propertyId ), args.rval().address() );",
        "}",
        "",
        "static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, const char *name )",
        "{",
        "\tauto args = JS::CallArgsFromVp( argc, vp );",
        "\tJS::RootedObject obj( cx );",
        "\tif( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, name, 1 )) return false;",
        "\tJS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));",
        "\tif( !property ) return false;",
        "\tJS::RootedId id( cx );",
        "\tif( !JS_StringToId( cx, property, &id )) return false;",
        "\tJS::RootedValue value( cx, args.get( 0 ));",
        "\targs.rval().setUndefined();",
        "\treturn setter( cx, obj, id, false, value.address() );",
        "}",
        "",
        "static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, int32_t propertyId )",
        "{",
        "\tauto args = JS::CallArgsFromVp( argc, vp );",
        "\tJS::RootedObject obj( cx );",
        "\tif( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, \"property setter\", 1 )) return false;",
        "\tJS::RootedValue value( cx, args.get( 0 ));",
        "\targs.rval().setUndefined();",
        "\treturn setter( cx, obj, JS::PropertyKey::Int( propertyId ), false, value.address() );",
        "}",
        "",
    ]

    seen = set()
    for has_setter, main_name, attr in properties:
        key = (main_name, attr)
        if key in seen:
            continue
        seen.add(key)
        family = FAMILIES[main_name]
        if main_name in enum_maps:
            candidates = enum_maps[main_name]
            wanted = normalized(ENUM_PREFIXES[main_name] + attr)
            matches = [(token, value) for token, value in candidates.items() if token == wanted]
            if not matches and attr.endswith("s"):
                wanted = normalized(ENUM_PREFIXES[main_name] + attr[:-1])
                matches = [(token, value) for token, value in candidates.items() if token == wanted]
            if len(matches) != 1:
                raise RuntimeError(f"Cannot map {main_name}.{attr}: {matches}")
            property_arg = str(matches[0][1])
        elif main_name == "CSkills":
            property_arg = str(skill_ids[normalized(attr)])
        else:
            property_arg = f'"{attr}"'

        lines.append(
            f"bool JS{main_name}_get_{attr}( JSContext *cx, unsigned argc, JS::Value *vp ) "
            f"{{ return LegacyGet( cx, argc, vp, {family}_getProperty, {property_arg} ); }}"
        )
        if has_setter:
            lines.append(
                f"bool JS{main_name}_set_{attr}( JSContext *cx, unsigned argc, JS::Value *vp ) "
                f"{{ return LegacySet( cx, argc, vp, {family}_setProperty, {property_arg} ); }}"
            )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
