//o------------------------------------------------------------------------------------------------o
//|	File		-	UOXJSPropertyFuncts.cpp
//|	Date		-	12/14/2001
//o------------------------------------------------------------------------------------------------o
//|	Notes		-	1.0		14th December, 2001 Initial implementation
//|							Defines the property specifications for race, region, guild,
//|							item and chars
//o------------------------------------------------------------------------------------------------o
#ifndef __UOXJSPropertySpecs__
#define __UOXJSPropertySpecs__

#include "UOXJSPropertyEnums.h"
#include "enums.h"


inline JSPropertySpec CSpellProperties[] =
{
	{ "id",					CSP_ID,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "action",				CSP_ACTION,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "delay",				CSP_DELAY,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageDelay",		CSP_DAMAGEDELAY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "recoveryDelay",		CSP_RECOVERYDELAY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "health",				CSP_HEALTH,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stamina",			CSP_STAMINA,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mana",				CSP_MANA,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mantra",				CSP_MANTRA,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name",				CSP_NAME,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "strToSay",			CSP_STRTOSAY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scrollLow",			CSP_SCROLLLOW,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scrollHigh",			CSP_SCROLLHIGH,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "circle",				CSP_CIRCLE,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lowSkill",			CSP_LOWSKILL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "highSkill",			CSP_HIGHSKILL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ginseng",			CSP_GINSENG,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "moss",				CSP_MOSS,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "drake",				CSP_DRAKE,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pearl",				CSP_PEARL,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "silk",				CSP_SILK,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ash",				CSP_ASH,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "shade",				CSP_SHADE,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "garlic",				CSP_GARLIC,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "requireTarget",		CSP_REQUIRETARGET,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "requireItem",		CSP_REQUIREITEM,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "requireLocation",    CSP_REQUIRELOCATION,    JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "requireChar",		CSP_REQUIRECHAR,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "travelSpell",		CSP_TRAVELSPELL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fieldSpell",			CSP_FIELDSPELL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "reflectable",		CSP_REFLECTABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "aggressiveSpell",	CSP_AGGRESSIVESPELL,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistable",			CSP_RESISTABLE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "soundEffect",		CSP_SOUNDEFFECT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "enabled",			CSP_ENABLED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "baseDmg",			CSP_BASEDMG,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CGlobalSkillProperties[] =
{
	{ "name",				CGSKILL_NAME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "madeWord",			CGSKILL_MADEWORD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "strength",			CGSKILL_STRENGTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "dexterity",			CGSKILL_DEXTERITY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "intelligence",		CGSKILL_INTELLIGENCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillDelay",			CGSKILL_SKILLDELAY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scriptID",			CGSKILL_SCRIPTID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CCreateEntryProperties[] =
{
	{ "id",					CMAKE_ID,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name",				CMAKE_NAME,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "addItem",			CMAKE_ADDITEM,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "colour",				CMAKE_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "sound",				CMAKE_SOUND,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "minRank",			CMAKE_MINRANK,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxRank",			CMAKE_MAXRANK,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "delay",				CMAKE_DELAY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spell",				CMAKE_SPELL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resources",			CMAKE_RESOURCES,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skills",				CMAKE_SKILLS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "avgMinSkill",		CMAKE_AVGMINSKILL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "avgMaxSkill",		CMAKE_AVGMAXSKILL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CTimerProperties[] =
{
	// Character Timers
	{ "TIMEOUT",			TIMER_TIMEOUT,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "INVIS",				TIMER_INVIS,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "HUNGER",				TIMER_HUNGER,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "THIRST",				TIMER_THIRST,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "POISONTIME",			TIMER_POISONTIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "POISONTEXT",			TIMER_POISONTEXT,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "POISONWEAROFF",		TIMER_POISONWEAROFF,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SPELLTIME",			TIMER_SPELLTIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SPELLRECOVERYTIME",	TIMER_SPELLRECOVERYTIME,JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "CRIMFLAG",			TIMER_CRIMFLAG,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "ANTISPAM",			TIMER_ANTISPAM,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "MURDERRATE",			TIMER_MURDERRATE,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "PEACETIMER",			TIMER_PEACETIMER,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "FLYINGTOGGLE",		TIMER_FLYINGTOGGLE,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "FIREFIELDTICK",		TIMER_FIREFIELDTICK,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "POISONFIELDTICK",	TIMER_POISONFIELDTICK,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "PARAFIELDTICK",		TIMER_PARAFIELDTICK,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "MOVETIME",			TIMER_MOVETIME,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SPATIMER",			TIMER_SPATIMER,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SUMMONTIME",			TIMER_SUMMONTIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "EVADETIME",			TIMER_EVADETIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "LOYALTYTIME",		TIMER_LOYALTYTIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "IDLEANIMTIME",		TIMER_IDLEANIMTIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "LOGOUT",				TIMER_LOGOUT,			JSPROP_ENUMPERMRO, nullptr, nullptr },

	// Socket Timers
	{ "SOCK_SKILLDELAY",		TIMER_SOCK_SKILLDELAY,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_OBJDELAY",			TIMER_SOCK_OBJDELAY,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_SPIRITSPEAK",		TIMER_SOCK_SPIRITSPEAK,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_TRACKING",			TIMER_SOCK_TRACKING,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_FISHING",			TIMER_SOCK_FISHING,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_MUTETIME",			TIMER_SOCK_MUTETIME,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_TRACKINGDISPLAY",	TIMER_SOCK_TRACKINGDISPLAY,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "SOCK_TRAFFICWARDEN",		TIMER_SOCK_TRAFFICWARDEN,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ nullptr,					static_cast<SI08>(0),		static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CRaceProperties[] =
{
	{ "id",					CRP_ID,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name",				CRP_NAME,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "weakToWeather",		CRP_WEAKTOWEATHER,		JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "requiresBeard",		CRP_REQUIRESBEARD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "requiresNoBeard",	CRP_REQUIRESNOBEARD,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isPlayerRace",		CRP_ISPLAYERRACE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "genderRestrict",		CRP_GENDERRESTRICT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "armourClass",		CRP_ARMOURCLASS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "languageSkillMin",	CRP_LANGUAGESKILLMIN,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillAdjustment",	CRP_SKILLADJUSTMENT,	JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "poisonResistance",	CRP_POISONRESISTANCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "magicResistance",	CRP_MAGICRESISTANCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "visibleDistance",	CRP_VISIBLEDISTANCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "nightVision",		CRP_NIGHTVISION,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};


inline JSPropertySpec CRegionProperties[] =
{
	{ "name",				CREGP_NAME,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mayor",				CREGP_MAYOR,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "race",				CREGP_RACE,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tax",				CREGP_TAX,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "taxResource",		CREGP_TAXRESOURCE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canMark",			CREGP_CANMARK,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canRecall",			CREGP_CANRECALL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canGate",			CREGP_CANGATE,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canTeleport",		CREGP_CANTELEPORT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canPlaceHouse",		CREGP_CANPLACEHOUSE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGuarded",			CREGP_ISGUARDED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canCastAggressive",	CREGP_CANCASTAGGRESSIVE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSafeZone",			CREGP_ISSAFEZONE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "health",				CREGP_HEALTH,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDungeon",			CREGP_ISDUNGEON,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "worldNumber",		CREGP_WORLDNUMBER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "instanceID",			CREGP_INSTANCEID,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "chanceBigOre",		CREGP_CHANCEBIGORE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "numOrePrefs",		CREGP_NUMOREPREFERENCES,	JSPROP_ENUMPERMRO, nullptr, nullptr  },
	{ "population",			CREGP_POPULATION,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "members",			CREGP_MEMBERS,				JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "id",					CREGP_ID,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scriptTrigger",		CREGP_SCRIPTTRIGGER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scriptTriggers",		CREGP_SCRIPTTRIGGERS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "numGuards",			CREGP_NUMGUARDS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "taxes",				CREGP_TAXES,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "reserves",			CREGP_RESERVES,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "appearance",			CREGP_APPEARANCE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "music",				CREGP_MUSIC,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "weather",			CREGP_WEATHER,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "owner",				CREGP_OWNER,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),		static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CSpawnRegionProperties[] =
{
	{ "name",				CSPAWNREGP_NAME,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "regionNum",			CSPAWNREGP_REGIONNUM,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "itemList",			CSPAWNREGP_ITEMLIST,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "npcList",			CSPAWNREGP_NPCLIST,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "item",				CSPAWNREGP_ITEM,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "npc",				CSPAWNREGP_NPC,						JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxItems",			CSPAWNREGP_MAXITEMS,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxNpcs",			CSPAWNREGP_MAXNPCS,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "itemCount",			CSPAWNREGP_ITEMCOUNT,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "npcCount",			CSPAWNREGP_NPCCOUNT,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "onlyOutside",		CSPAWNREGP_ONLYOUTSIDE,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSpawner",			CSPAWNREGP_ISSPAWNER,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "defZ",				CSPAWNREGP_DEFZ,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "prefZ",				CSPAWNREGP_PREFZ,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "x1",					CSPAWNREGP_X1,						JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "y1",					CSPAWNREGP_X2,						JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "x2",					CSPAWNREGP_X2,						JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "y2",					CSPAWNREGP_Y2,						JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "world",				CSPAWNREGP_WORLD,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "instanceID",			CSPAWNREGP_INSTANCEID,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "minTime",			CSPAWNREGP_MINTIME,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxTime",			CSPAWNREGP_MAXTIME,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "call",				CSPAWNREGP_CALL,					JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),				static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CGuildProperties[] =
{
	{ "name",			CGP_NAME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "type",			CGP_TYPE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "master",			CGP_MASTER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stone",			CGP_STONE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "numMembers",		CGP_NUMMEMBERS,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "numRecruits",	CGP_NUMRECRUITS,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "members",		CGP_MEMBERS,		JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "recruits",		CGP_RECRUITS,		JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "charter",		CGP_CHARTER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "abbreviation",	CGP_ABBREVIATION,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "webPage",		CGP_WEBPAGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,			static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CCharacterProps[] =
{
	{ "sectionID",		CCP_SECTIONID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name",			CCP_NAME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "origName",		CCP_ORIGNAME,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "title",			CCP_TITLE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "x",				CCP_X,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "y",				CCP_Y,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "z",				CCP_Z,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldX",			CCP_OLDX,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldY",			CCP_OLDY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldZ",			CCP_OLDZ,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "id",				CCP_ID,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "colour",			CCP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "color",			CCP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skin",			CCP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hue",			CCP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "controlSlots",	CCP_CONTROLSLOTS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "controlSlotsUsed",	CCP_CONTROLSLOTSUSED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "orneriness",		CCP_ORNERINESS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "owner",			CCP_OWNER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "visible",		CCP_VISIBLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "serial",			CCP_SERIAL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "health",			CCP_HEALTH,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scripttrigger",	CCP_SCRIPTTRIGGER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scriptTriggers",	CCP_SCRIPTTRIGGERS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "worldnumber",	CCP_WORLDNUMBER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "instanceID",		CCP_INSTANCEID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "target",			CCP_TARGET,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "dexterity",		CCP_DEXTERITY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "intelligence",	CCP_INTELLIGENCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "strength",		CCP_STRENGTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "actualDexterity",	CCP_ACTUALDEXTERITY,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "actualIntelligence",	CCP_ACTUALINTELLIGENCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "actualStrength",		CCP_ACTUALSTRENGTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skills",			CCP_SKILLS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mana",			CCP_MANA,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stamina",		CCP_STAMINA,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pack",			CCP_CHARPACK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fame",			CCP_FAME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "karma",			CCP_KARMA,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "attack",			CCP_ATTACK,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "canAttack",		CCP_CANATTACK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fleeAt",			CCP_FLEEAT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "reAttackAt",		CCP_REATTACKAT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "brkPeaceChance",	CCP_BRKPEACE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "setPeace",		CCP_SETPEACE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hunger",			CCP_HUNGER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hungerRate",		CCP_HUNGERRATE,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "thirst",			CCP_THIRST,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "thirstRate",		CCP_THIRSTRATE,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "frozen",			CCP_FROZEN,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "commandlevel",	CCP_COMMANDLEVEL,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "race",			CCP_RACE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hasStolen",		CCP_HASSTOLEN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "criminal",		CCP_CRIMINAL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "murderer",		CCP_MURDERER,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "innocent",		CCP_INNOCENT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "murdercount",	CCP_MURDERCOUNT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "neutral",		CCP_NEUTRAL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "npcFlag",		CCP_NPCFLAG,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "npcGuild",		CCP_NPCGUILD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "gender",			CCP_GENDER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "dead",			CCP_DEAD,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "npc",			CCP_NPC,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isAwake",		CCP_AWAKE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "online",			CCP_ONLINE,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "direction",		CCP_DIRECTION,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isRunning",		CCP_ISRUNNING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "region",			CCP_REGION,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "town",			CCP_TOWN,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "guild",			CCP_GUILD,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "baseskills",		CCP_BASESKILLS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillsused",		CCP_SKILLUSE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "socket",			CCP_SOCKET,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isChar",			CCP_ISCHAR,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isItem",			CCP_ISITEM,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isSpawner",		CCP_ISSPAWNER,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "spawnSerial",	CCP_SPAWNSERIAL,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "maxhp",			CCP_MAXHP,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxstamina",		CCP_MAXSTAMINA,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxmana",		CCP_MAXMANA,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldWandertype",	CCP_OLDWANDERTYPE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "wandertype",		CCP_WANDERTYPE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fx1",			CCP_FX1,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fy1",			CCP_FY1,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fx2",			CCP_FX2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fy2",			CCP_FY2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fz",				CCP_FZ,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isonhorse",		CCP_ISONHORSE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isFlying",		CCP_ISFLYING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGuarded",		CCP_ISGUARDED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "guarding",		CCP_GUARDING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempdex",		CCP_TDEXTERITY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempint",		CCP_TINTELLIGENCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempstr",		CCP_TSTRENGTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "poison",			CCP_POISON,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lightlevel",		CCP_LIGHTLEVEL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "vulnerable",		CCP_VULNERABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "willhunger",		CCP_HUNGERSTATUS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "willthirst",		CCP_THIRSTSTATUS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lodamage",		CCP_LODAMAGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hidamage",		CCP_HIDAMAGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "flag",			CCP_FLAG,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "atWar",			CCP_ATWAR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spellCast",		CCP_SPELLCAST,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isCasting",		CCP_ISCASTING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "priv",			CCP_PRIV,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "townPriv",		CCP_TOWNPRIV,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "guildTitle",		CCP_GUILDTITLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hairStyle",		CCP_HAIRSTYLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hairColour",		CCP_HAIRCOLOUR,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hairColor",		CCP_HAIRCOLOUR,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "beardStyle",		CCP_BEARDSTYLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "beardColour",	CCP_BEARDCOLOUR,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "beardColor",		CCP_BEARDCOLOUR,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fontType",		CCP_FONTTYPE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "sayColour",		CCP_SAYCOLOUR,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "emoteColour",	CCP_EMOTECOLOUR,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "attacker",		CCP_ATTACKER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "raceGate",		CCP_RACEGATE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillLock",		CCP_SKILLLOCK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "deaths",			CCP_DEATHS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ownerCount",		CCP_OWNERCOUNT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "nextAct",		CCP_NEXTACT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "petCount",		CCP_PETCOUNT,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "followerCount",	CCP_FOLLOWERCOUNT,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "ownedItemsCount",CCP_OWNEDITEMSCOUNT,JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "cell",			CCP_CELL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "allmove",		CCP_ALLMOVE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "houseicons",		CCP_HOUSEICONS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spattack",		CCP_SPATTACK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spdelay",		CCP_SPDELAY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "aitype",			CCP_AITYPE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "split",			CCP_SPLIT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "splitchance",	CCP_SPLITCHANCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hireling",		CCP_HIRELING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "trainer",		CCP_TRAINER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "weight",			CCP_WEIGHT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "squelch",		CCP_SQUELCH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isJailed",		CCP_ISJAILED,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "magicReflect",	CCP_MAGICREFLECT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "permanentMagicReflect",	CCP_PERMMAGICREFLECT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tamed",			CCP_TAMED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tamedHungerRate",CCP_TAMEDHUNGERRATE,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tamedThirstRate",CCP_TAMEDTHIRSTRATE,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hungerWildChance",CCP_HUNGERWILDCHANCE,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "thirstWildChance",CCP_THIRSTWILDCHANCE,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "foodList",		CCP_FOODLIST,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mounted",		CCP_MOUNTED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stabled",		CCP_STABLED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isUsingPotion",	CCP_USINGPOTION,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stealth",		CCP_STEALTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillToTame",	CCP_SKILLTOTAME,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillToProv",	CCP_SKILLTOPROV,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skillToPeace",	CCP_SKILLTOPEACE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "poisonStrength",	CCP_POISONSTRENGTH,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isPolymorphed",	CCP_ISPOLYMORPHED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isIncognito",	CCP_ISINCOGNITO,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDisguised",	CCP_ISDISGUISED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canRun",			CCP_CANRUN,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isMeditating",	CCP_ISMEDITATING,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGM",			CCP_ISGM,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canBroadcast",	CCP_CANBROADCAST,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "singClickSer",	CCP_SINGCLICKSER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "noSkillTitles",	CCP_NOSKILLTITLES,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGMPageable",	CCP_ISGMPAGEABLE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "canSnoop",		CCP_CANSNOOP,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isCounselor",	CCP_ISCOUNSELOR,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "noNeedMana",		CCP_NONEEDMANA,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDispellable",	CCP_ISDISPELLABLE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "noNeedReags",	CCP_NONEEDREAGS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "orgID",			CCP_ORGID,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "orgSkin",		CCP_ORGSKIN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isAnimal",		CCP_ISANIMAL,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isHuman",		CCP_ISHUMAN,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isShop",			CCP_ISSHOP,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxLoyalty",		CCP_MAXLOYALTY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "loyalty",		CCP_LOYALTY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "loyaltyRate",	CCP_LOYALTYRATE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "shouldSave",		CCP_SHOULDSAVE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "origin",			CCP_ORIGIN,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "partyLootable",	CCP_PARTYLOOTABLE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "party",			CCP_PARTY,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "multi",			CCP_MULTI,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "accountNum",		CCP_ACCOUNTNUM,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "account",		CCP_ACCOUNT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "createdOn",		CCP_CREATEDON,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "playTime",		CCP_PLAYTIME,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "housesOwned",	CCP_HOUSESOWNED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "housesCoOwned",	CCP_HOUSESCOOWNED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,			static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CItemProps[] =
{
	{ "sectionID",		CIP_SECTIONID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name",			CIP_NAME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "title",			CIP_TITLE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "x",				CIP_X,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "y",				CIP_Y,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "z",				CIP_Z,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldX",			CIP_OLDX,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldY",			CIP_OLDY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oldZ",			CIP_OLDZ,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "id",				CIP_ID,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "colour",			CIP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "color",			CIP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "skin",			CIP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hue",			CIP_COLOUR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "owner",			CIP_OWNER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "visible",		CIP_VISIBLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "serial",			CIP_SERIAL,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "health",			CIP_HEALTH,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scripttrigger",	CIP_SCRIPTTRIGGER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "scriptTriggers",	CIP_SCRIPTTRIGGERS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "worldnumber",	CIP_WORLDNUMBER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "instanceID",		CIP_INSTANCEID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "amount",			CIP_AMOUNT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "container",		CIP_CONTAINER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "type",			CIP_TYPE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "more",			CIP_MORE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "more0",			CIP_MORE0,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "more1",			CIP_MORE1,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "more2",			CIP_MORE2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "morex",			CIP_MOREX,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "morey",			CIP_MOREY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "morez",			CIP_MOREZ,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "movable",		CIP_MOVABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "att",			CIP_ATT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "layer",			CIP_LAYER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "itemsinside",	CIP_ITEMSINSIDE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "totalItemCount",	CIP_TOTALITEMCOUNT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "decayable",		CIP_DECAYABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "decaytime",		CIP_DECAYTIME,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lodamage",		CIP_LODAMAGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hidamage",		CIP_HIDAMAGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ac",				CIP_AC,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "def",			CIP_DEF,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistCold",		CIP_RESISTCOLD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistHeat",		CIP_RESISTHEAT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistLight",	CIP_RESISTLIGHT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistLightning",CIP_RESISTLIGHTNING,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistPoison",	CIP_RESISTPOISON,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistRain",		CIP_RESISTRAIN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "resistSnow",		CIP_RESISTSNOW,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageHeat",		CIP_DAMAGEHEAT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageCold",		CIP_DAMAGECOLD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageLight",	CIP_DAMAGELIGHT,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageLightning",CIP_DAMAGELIGHTNING,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damagePoison",	CIP_DAMAGEPOISON,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageRain",		CIP_DAMAGERAIN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "damageSnow",		CIP_DAMAGESNOW,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "name2",			CIP_NAME2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isChar",			CIP_ISCHAR,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isItem",			CIP_ISITEM,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isSpawner",		CIP_ISSPAWNER,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "race",			CIP_RACE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxhp",			CIP_MAXHP,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxUses",		CIP_MAXUSES,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "usesLeft",		CIP_USESLEFT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "rank",			CIP_RANK,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "creator",		CIP_CREATOR,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "poison",			CIP_POISON,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "dir",			CIP_DIR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "wipable",		CIP_WIPABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "buyvalue",		CIP_BUYVALUE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "sellvalue",		CIP_SELLVALUE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "vendorPrice",	CIP_VENDORPRICE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "restock",		CIP_RESTOCK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "good",			CIP_GOOD,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "divinelock",		CIP_DIVINELOCK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "baseWeight",		CIP_BASEWEIGHT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "weight",			CIP_WEIGHT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "weightMax",		CIP_WEIGHTMAX,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxItems",		CIP_MAXITEMS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "strength",		CIP_STRENGTH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "dexterity",		CIP_DEXTERITY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "intelligence",	CIP_INTELLIGENCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "corpse",			CIP_CORPSE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "desc",			CIP_DESC,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "event",			CIP_EVENT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempLastTraded",	CIP_TEMPLASTTRADED,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempTimer",		CIP_TEMPTIMER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "shouldSave",		CIP_SHOULDSAVE,		JSPROP_ENUMANDPERM, nullptr, nullptr },

	{ "isNewbie",		CIP_ISNEWBIE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDispellable",	CIP_ISDISPELLABLE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "madeWith",		CIP_MADEWITH,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "entryMadeFrom",	CIP_ENTRYMADEFROM,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isPileable",		CIP_ISPILEABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isMarkedByMaker",CIP_ISMARKEDBYMAKER,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDyeable",		CIP_ISDYEABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDamageable",	CIP_ISDAMAGEABLE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isWipeable",		CIP_ISWIPEABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGuarded",		CIP_ISGUARDED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isDoorOpen",		CIP_ISDOOROPEN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isFieldSpell",	CIP_ISFIELDSPELL,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isLockedDown",	CIP_ISLOCKEDDOWN,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isShieldType",	CIP_ISSHIELDTYPE,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isMetalType",	CIP_ISMETALTYPE,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isLeatherType",	CIP_ISLEATHERTYPE,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "canBeLockedDown",CIP_CANBELOCKEDDOWN,JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "isContType",		CIP_ISCONTTYPE,		JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "carveSection",	CIP_CARVESECTION,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ammoID",			CIP_AMMOID,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ammoHue",		CIP_AMMOHUE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ammoFX",			CIP_AMMOFX,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ammoFXHue",		CIP_AMMOFXHUE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ammoFXRender",	CIP_AMMOFXRENDER,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "speed",			CIP_SPEED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "artifactRarity",	CIP_ARTIFACTRARITY,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "multi",			CIP_MULTI,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxRange",		CIP_MAXRANGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "baseRange",		CIP_BASERANGE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "region",			CIP_REGION,			JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "spawnSerial",	CIP_SPAWNSERIAL,	JSPROP_ENUMPERMRO, nullptr, nullptr },
	{ "origin",			CIP_ORIGIN,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isItemHeld",		CIP_ISITEMHELD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stealable",		CIP_STEALABLE,		JSPROP_ENUMANDPERM, nullptr, nullptr },

	// The Following vars are specific to CSpawnItem objects
	{ "spawnsection",	CIP_SPAWNSECTION,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "sectionalist",	CIP_SECTIONALIST,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mininterval",	CIP_MININTERVAL,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxinterval",	CIP_MAXINTERVAL,	JSPROP_ENUMANDPERM, nullptr, nullptr },

	// The Following vars are specific to cMultiObj objects
	{ "lockdowns",		CIP_LOCKDDOWNS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxLockdowns",	CIP_MAXLOCKDOWNS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "trashContainers",	CIP_TRASHCONTAINERS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxTrashContainers",	CIP_MAXTRASHCONTAINERS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "secureContainers",	CIP_SECURECONTAINERS,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxSecureContainers",CIP_MAXSECURECONTAINERS,JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "friends",		CIP_FRIENDS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxFriends",		CIP_MAXFRIENDS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "guests",			CIP_GUESTS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxGuests",		CIP_MAXGUESTS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "owners",			CIP_OWNERS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxOwners",		CIP_MAXOWNERS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "bans",			CIP_BANS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxBans",		CIP_MAXBANS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "vendors",		CIP_VENDORS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "maxVendors",		CIP_MAXVENDORS,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "deed",			CIP_DEED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isPublic",		CIP_ISPUBLIC,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "buildTimestamp",	CIP_BUILDTIMESTAMP,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tradeTimestamp",	CIP_TRADETIMESTAMP,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "banX",			CIP_BANX,			JSPROP_ENUMANDPERM, nullptr, nullptr},
	{ "banY",			CIP_BANY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,			static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CSocketProps[] =
{
	{ "account",			CSOCKP_ACCOUNT,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "currentChar",		CSOCKP_CURRENTCHAR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "idleTimeout",		CSOCKP_IDLETIMEOUT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "wasIdleWarned",		CSOCKP_WASIDLEWARNED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempInt",			CSOCKP_TEMPINT,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempInt2",			CSOCKP_TEMPINT2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "buffer",				CSOCKP_BUFFER,				JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "xText",				CSOCKP_XTEXT,				JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "xText2",				CSOCKP_XTEXT2,				JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "clickZ",				CSOCKP_CLICKZ,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "addID",				CSOCKP_ADDID,				JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "newClient",			CSOCKP_NEWCLIENT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "firstPacket",		CSOCKP_FIRSTPACKET,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "cryptClient",		CSOCKP_CRYPTCLIENT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientIP",			CSOCKP_CLIENTIP,			JSPROP_ENUMPERMIDX, nullptr, nullptr },
	{ "walkSequence",		CSOCKP_WALKSEQUENCE,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "currentSpellType",	CSOCKP_CURRENTSPELLTYPE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "logging",			CSOCKP_LOGGING,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "bytesSent",			CSOCKP_BYTESSENT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "bytesReceived",		CSOCKP_BYTESRECEIVED,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "targetOK",			CSOCKP_TARGETOK,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clickX",				CSOCKP_CLICKX,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clickY",				CSOCKP_CLICKY,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pickupX",			CSOCKP_PICKUPX,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pickupY",			CSOCKP_PICKUPY,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pickupZ",			CSOCKP_PICKUPZ,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pickupSpot",			CSOCKP_PICKUPSPOT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "pickupSerial",		CSOCKP_PICKUPSERIAL,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "language",			CSOCKP_LANGUAGE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientMajorVer",		CSOCKP_CLIENTMAJORVER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientMinorVer",		CSOCKP_CLIENTMINORVER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientSubVer",		CSOCKP_CLIENTSUBVER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientLetterVer",	CSOCKP_CLIENTLETTERVER,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "clientType",			CSOCKP_CLIENTTYPE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "target",				CSOCKP_TARGET,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempObj",			CSOCKP_TEMPOBJ,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tempObj2",			CSOCKP_TEMPOBJ2,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),		static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CSkillsProps[] =
{
	{ "alchemy",			ALCHEMY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "anatomy",			ANATOMY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "animallore",			ANIMALLORE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "itemid",				ITEMID,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "armslore",			ARMSLORE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "parrying",			PARRYING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "begging",			BEGGING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "blacksmithing",		BLACKSMITHING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "bowcraft",			BOWCRAFT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "peacemaking",		PEACEMAKING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "camping",			CAMPING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "carpentry",			CARPENTRY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "cartography",		CARTOGRAPHY,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "cooking",			COOKING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "detectinghidden",	DETECTINGHIDDEN,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "enticement",			ENTICEMENT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "evaluatingintel",	EVALUATINGINTEL,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "healing",			HEALING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fishing",			FISHING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "forensics",			FORENSICS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "herding",			HERDING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "hiding",				HIDING,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "provocation",		PROVOCATION,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "inscription",		INSCRIPTION,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lockpicking",		LOCKPICKING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "magery",				MAGERY,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "magicresistance",	MAGICRESISTANCE,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tactics",			TACTICS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "snooping",			SNOOPING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "musicianship",		MUSICIANSHIP,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "poisoning",			POISONING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "archery",			ARCHERY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spiritspeak",		SPIRITSPEAK,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stealing",			STEALING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tailoring",			TAILORING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "taming",				TAMING,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tasteid",			TASTEID,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tinkering",			TINKERING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "tracking",			TRACKING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "veterinary",			VETERINARY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "swordsmanship",		SWORDSMANSHIP,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "macefighting",		MACEFIGHTING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fencing",			FENCING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "wrestling",			WRESTLING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lumberjacking",		LUMBERJACKING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mining",				MINING,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "meditation",			MEDITATION,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "stealth",			STEALTH,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "removetrap",			REMOVETRAP,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "necromancy",			NECROMANCY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "focus",				FOCUS,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "chivalry",			CHIVALRY,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "bushido",			BUSHIDO,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "ninjitsu",			NINJITSU,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "spellweaving",		SPELLWEAVING,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "mysticism",			MYSTICISM,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "imbuing",			IMBUING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "throwing",			THROWING,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "allskills",			ALLSKILLS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ nullptr,				static_cast<SI08>(0),			static_cast<UI08>(0), nullptr, nullptr }
};

inline JSPropertySpec CGumpDataProperties[] =
{
	{	"buttons",	CGumpData_Button,		JSPROP_ENUMANDPERM, nullptr, nullptr	},
	{	"IDs",		CGumpData_ID ,			JSPROP_ENUMANDPERM, nullptr, nullptr	},
	{	nullptr,	static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CAccountProperties[] =
{
	{ "id",			CACCOUNT_ID,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "username",	CACCOUNT_USERNAME,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "password",	CACCOUNT_PASSWORD,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "flags",		CACCOUNT_FLAGS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "path",		CACCOUNT_PATH,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "comment",	CACCOUNT_COMMENT,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "timeban",	CACCOUNT_TIMEBAN,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "firstLogin",	CACCOUNT_FIRSTLOGIN, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "totalPlayTime",	CACCOUNT_TOTALPLAYTIME,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character1",	CACCOUNT_CHARACTER1, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character2",	CACCOUNT_CHARACTER2, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character3",	CACCOUNT_CHARACTER3, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character4",	CACCOUNT_CHARACTER4, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character5",	CACCOUNT_CHARACTER5, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character6",	CACCOUNT_CHARACTER6, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "character7",	CACCOUNT_CHARACTER7, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "currentChar",	CACCOUNT_CURRENTCHAR,	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "lastIP",			CACCOUNT_LASTIP, 		JSPROP_ENUMANDPERM, nullptr, nullptr },

	// Flags
	{ "isBanned",		CACCOUNT_BANNED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSuspended",	CACCOUNT_SUSPENDED,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isPublic",		CACCOUNT_PUBLIC,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isOnline",		CACCOUNT_ONLINE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot1Blocked",	CACCOUNT_CHARSLOT1BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot2Blocked",	CACCOUNT_CHARSLOT2BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot3Blocked",	CACCOUNT_CHARSLOT3BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot4Blocked",	CACCOUNT_CHARSLOT4BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot5Blocked",	CACCOUNT_CHARSLOT5BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot6Blocked",	CACCOUNT_CHARSLOT6BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSlot7Blocked",	CACCOUNT_CHARSLOT7BLOCKED, 	JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isYoung",		CACCOUNT_YOUNG,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "unused10",		CACCOUNT_UNUSED10,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isSeer",			CACCOUNT_SEER,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isCounselor",	CACCOUNT_COUNSELOR,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "isGM",			CACCOUNT_GM,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,		static_cast<SI08>(0),		static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CConsoleProperties[] =
{
	{ "mode",		CCONSOLE_MODE,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "logEcho",	CCONSOLE_LOGECHO,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,	static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CScriptSectionProperties[] =
{
	{ "numTags",	CSS_NUMTAGS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "atEnd",		CSS_ATEND,				JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "atEndTags",	CSS_ATENDTAGS,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,	static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CResourceProperties[] =
{
	{ "logAmount",	CRESP_LOGAMT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "logTime",	CRESP_LOGTIME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oreAmount",	CRESP_OREAMT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "oreTime",	CRESP_ORETIME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fishAmount",	CRESP_FISHAMT,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "fishTime",	CRESP_FISHTIME,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,	static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CPartyProperties[] =
{
	{ "leader",			CPARTYP_LEADER,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{ "memberCount",	CPARTYP_MEMBERCOUNT,	JSPROP_ENUMPERMRO, nullptr, nullptr	},
	{ "isNPC",			CPARTYP_ISNPC,			JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,		static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

inline JSPropertySpec CScriptProperties[] =
{
	{ "script_id",		CSCRIPT_SCRIPTID,		JSPROP_ENUMANDPERM, nullptr, nullptr },
	{	nullptr,		static_cast<SI08>(0),	static_cast<UI08>(0), nullptr, nullptr	}
};

#endif
