// Generated by tools/generate_mozjs_property_adapters.py.
#include "uox3.h"
#include "UOXJSPropertyFuncs.h"

using LegacyGetter = bool (*)( JSContext *, JSObject *, jsid, JS::Value * );
using LegacySetter = bool (*)( JSContext *, JSObject *, jsid, bool, JS::Value * );

static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, const char *name )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj )) return false;
	JS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));
	if( !property ) return false;
	JS::RootedId id( cx );
	if( !JS_StringToId( cx, property, &id )) return false;
	return getter( cx, obj, id, args.rval().address() );
}

static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, int32_t propertyId )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj )) return false;
	return getter( cx, obj, JS::PropertyKey::Int( propertyId ), args.rval().address() );
}

static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, const char *name )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, name, 1 )) return false;
	JS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));
	if( !property ) return false;
	JS::RootedId id( cx );
	if( !JS_StringToId( cx, property, &id )) return false;
	JS::RootedValue value( cx, args.get( 0 ));
	args.rval().setUndefined();
	return setter( cx, obj, id, false, value.address() );
}

static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, int32_t propertyId )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, "property setter", 1 )) return false;
	JS::RootedValue value( cx, args.get( 0 ));
	args.rval().setUndefined();
	return setter( cx, obj, JS::PropertyKey::Int( propertyId ), false, value.address() );
}

