// Generated by tools/generate_mozjs_property_adapters.py.
#include "uox3.h"
#include "UOXJSPropertyFuncs.h"

using LegacyGetter = bool (*)( JSContext *, JSObject *, jsid, JS::Value * );
using LegacySetter = bool (*)( JSContext *, JSObject *, jsid, bool, JS::Value * );

static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, const char *name )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj )) return false;
	JS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));
	if( !property ) return false;
	JS::RootedId id( cx );
	if( !JS_StringToId( cx, property, &id )) return false;
	return getter( cx, obj, id, args.rval().address() );
}

static bool LegacyGet( JSContext *cx, unsigned argc, JS::Value *vp, LegacyGetter getter, int32_t propertyId )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj )) return false;
	return getter( cx, obj, JS::PropertyKey::Int( propertyId ), args.rval().address() );
}

static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, const char *name )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, name, 1 )) return false;
	JS::RootedString property( cx, JS_NewStringCopyZ( cx, name ));
	if( !property ) return false;
	JS::RootedId id( cx );
	if( !JS_StringToId( cx, property, &id )) return false;
	JS::RootedValue value( cx, args.get( 0 ));
	args.rval().setUndefined();
	return setter( cx, obj, id, false, value.address() );
}

static bool LegacySet( JSContext *cx, unsigned argc, JS::Value *vp, LegacySetter setter, int32_t propertyId )
{
	auto args = JS::CallArgsFromVp( argc, vp );
	JS::RootedObject obj( cx );
	if( !args.computeThis( cx, &obj ) || !args.requireAtLeast( cx, "property setter", 1 )) return false;
	JS::RootedValue value( cx, args.get( 0 ));
	args.rval().setUndefined();
	return setter( cx, obj, JS::PropertyKey::Int( propertyId ), false, value.address() );
}

bool JSCCharacter_get_owner( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 14 ); }
bool JSCCharacter_set_owner( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 14 ); }
bool JSCCharacter_get_scripttrigger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 18 ); }
bool JSCCharacter_set_scripttrigger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 18 ); }
bool JSCCharacter_get_scriptTriggers( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 19 ); }
bool JSCCharacter_set_scriptTriggers( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 19 ); }
bool JSCCharacter_get_target( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 22 ); }
bool JSCCharacter_set_target( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 22 ); }
bool JSCCharacter_get_dexterity( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 23 ); }
bool JSCCharacter_set_dexterity( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 23 ); }
bool JSCCharacter_get_intelligence( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 24 ); }
bool JSCCharacter_set_intelligence( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 24 ); }
bool JSCCharacter_get_strength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 25 ); }
bool JSCCharacter_set_strength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 25 ); }
bool JSCCharacter_get_actualDexterity( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 26 ); }
bool JSCCharacter_set_actualDexterity( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 26 ); }
bool JSCCharacter_get_actualIntelligence( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 27 ); }
bool JSCCharacter_set_actualIntelligence( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 27 ); }
bool JSCCharacter_get_actualStrength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 28 ); }
bool JSCCharacter_set_actualStrength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 28 ); }
bool JSCCharacter_get_healthRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 29 ); }
bool JSCCharacter_set_healthRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 29 ); }
bool JSCCharacter_get_staminaRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 30 ); }
bool JSCCharacter_set_staminaRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 30 ); }
bool JSCCharacter_get_manaRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 31 ); }
bool JSCCharacter_set_manaRegenBonus( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 31 ); }
bool JSCCharacter_get_skills( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 32 ); }
bool JSCCharacter_set_skills( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 32 ); }
bool JSCCharacter_get_mana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 33 ); }
bool JSCCharacter_set_mana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 33 ); }
bool JSCCharacter_get_stamina( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 34 ); }
bool JSCCharacter_set_stamina( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 34 ); }
bool JSCCharacter_get_pack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 35 ); }
bool JSCCharacter_set_pack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 35 ); }
bool JSCCharacter_get_fame( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 36 ); }
bool JSCCharacter_set_fame( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 36 ); }
bool JSCCharacter_get_karma( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 37 ); }
bool JSCCharacter_set_karma( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 37 ); }
bool JSCCharacter_get_attack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 38 ); }
bool JSCCharacter_get_canAttack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 39 ); }
bool JSCCharacter_set_canAttack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 39 ); }
bool JSCCharacter_get_karmaLock( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 40 ); }
bool JSCCharacter_set_karmaLock( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 40 ); }
bool JSCCharacter_get_fleeAt( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 41 ); }
bool JSCCharacter_set_fleeAt( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 41 ); }
bool JSCCharacter_get_reAttackAt( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 42 ); }
bool JSCCharacter_set_reAttackAt( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 42 ); }
bool JSCCharacter_get_brkPeaceChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 43 ); }
bool JSCCharacter_set_brkPeaceChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 43 ); }
bool JSCCharacter_get_setPeace( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 44 ); }
bool JSCCharacter_set_setPeace( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 44 ); }
bool JSCCharacter_get_hunger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 45 ); }
bool JSCCharacter_set_hunger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 45 ); }
bool JSCCharacter_get_hungerRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 46 ); }
bool JSCCharacter_get_thirst( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 47 ); }
bool JSCCharacter_set_thirst( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 47 ); }
bool JSCCharacter_get_thirstRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 48 ); }
bool JSCCharacter_get_frozen( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 49 ); }
bool JSCCharacter_set_frozen( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 49 ); }
bool JSCCharacter_get_commandlevel( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 50 ); }
bool JSCCharacter_set_commandlevel( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 50 ); }
bool JSCCharacter_get_race( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 51 ); }
bool JSCCharacter_set_race( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 51 ); }
bool JSCCharacter_get_hasStolen( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 52 ); }
bool JSCCharacter_set_hasStolen( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 52 ); }
bool JSCCharacter_get_criminal( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 53 ); }
bool JSCCharacter_set_criminal( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 53 ); }
bool JSCCharacter_get_murderer( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 54 ); }
bool JSCCharacter_get_innocent( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 55 ); }
bool JSCCharacter_set_innocent( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 55 ); }
bool JSCCharacter_get_murdercount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 56 ); }
bool JSCCharacter_set_murdercount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 56 ); }
bool JSCCharacter_get_neutral( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 189 ); }
bool JSCCharacter_set_neutral( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 189 ); }
bool JSCCharacter_get_npcFlag( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 184 ); }
bool JSCCharacter_set_npcFlag( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 184 ); }
bool JSCCharacter_get_npcGuild( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 185 ); }
bool JSCCharacter_set_npcGuild( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 185 ); }
bool JSCCharacter_get_gender( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 57 ); }
bool JSCCharacter_set_gender( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 57 ); }
bool JSCCharacter_get_dead( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 58 ); }
bool JSCCharacter_get_npc( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 59 ); }
bool JSCCharacter_set_npc( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 59 ); }
bool JSCCharacter_get_isAwake( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 60 ); }
bool JSCCharacter_set_isAwake( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 60 ); }
bool JSCCharacter_get_online( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 61 ); }
bool JSCCharacter_get_direction( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 62 ); }
bool JSCCharacter_set_direction( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 62 ); }
bool JSCCharacter_get_isRunning( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 63 ); }
bool JSCCharacter_set_isRunning( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 63 ); }
bool JSCCharacter_get_region( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 64 ); }
bool JSCCharacter_set_region( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 64 ); }
bool JSCCharacter_get_town( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 65 ); }
bool JSCCharacter_set_town( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 65 ); }
bool JSCCharacter_get_guild( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 66 ); }
bool JSCCharacter_set_guild( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 66 ); }
bool JSCCharacter_get_guildNumber( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 67 ); }
bool JSCCharacter_set_guildNumber( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 67 ); }
bool JSCCharacter_get_baseskills( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 69 ); }
bool JSCCharacter_set_baseskills( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 69 ); }
bool JSCCharacter_get_skillsused( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 68 ); }
bool JSCCharacter_set_skillsused( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 68 ); }
bool JSCCharacter_get_socket( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 70 ); }
bool JSCCharacter_set_socket( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 70 ); }
bool JSCCharacter_get_isChar( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 72 ); }
bool JSCCharacter_get_isItem( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 71 ); }
bool JSCCharacter_get_isSpawner( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 128 ); }
bool JSCCharacter_get_spawnSerial( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 129 ); }
bool JSCCharacter_get_maxhp( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 73 ); }
bool JSCCharacter_set_maxhp( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 73 ); }
bool JSCCharacter_get_maxstamina( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 75 ); }
bool JSCCharacter_set_maxstamina( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 75 ); }
bool JSCCharacter_get_maxmana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 74 ); }
bool JSCCharacter_set_maxmana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 74 ); }
bool JSCCharacter_get_oldWandertype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 76 ); }
bool JSCCharacter_set_oldWandertype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 76 ); }
bool JSCCharacter_get_wandertype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 77 ); }
bool JSCCharacter_set_wandertype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 77 ); }
bool JSCCharacter_get_fx1( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 78 ); }
bool JSCCharacter_set_fx1( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 78 ); }
bool JSCCharacter_get_fy1( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 79 ); }
bool JSCCharacter_set_fy1( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 79 ); }
bool JSCCharacter_get_fx2( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 80 ); }
bool JSCCharacter_set_fx2( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 80 ); }
bool JSCCharacter_get_fy2( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 81 ); }
bool JSCCharacter_set_fy2( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 81 ); }
bool JSCCharacter_get_fz( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 82 ); }
bool JSCCharacter_set_fz( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 82 ); }
bool JSCCharacter_get_spawnX( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 83 ); }
bool JSCCharacter_set_spawnX( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 83 ); }
bool JSCCharacter_get_spawnY( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 84 ); }
bool JSCCharacter_set_spawnY( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 84 ); }
bool JSCCharacter_get_spawnZ( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 85 ); }
bool JSCCharacter_set_spawnZ( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 85 ); }
bool JSCCharacter_get_pathTargX( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 86 ); }
bool JSCCharacter_set_pathTargX( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 86 ); }
bool JSCCharacter_get_pathTargY( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 87 ); }
bool JSCCharacter_set_pathTargY( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 87 ); }
bool JSCCharacter_get_isonhorse( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 88 ); }
bool JSCCharacter_set_isonhorse( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 88 ); }
bool JSCCharacter_get_isFlying( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 89 ); }
bool JSCCharacter_set_isFlying( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 89 ); }
bool JSCCharacter_get_isGuarded( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 168 ); }
bool JSCCharacter_set_isGuarded( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 168 ); }
bool JSCCharacter_get_guarding( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 169 ); }
bool JSCCharacter_set_guarding( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 169 ); }
bool JSCCharacter_get_tempdex( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 90 ); }
bool JSCCharacter_set_tempdex( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 90 ); }
bool JSCCharacter_get_tempint( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 91 ); }
bool JSCCharacter_set_tempint( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 91 ); }
bool JSCCharacter_get_tempstr( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 92 ); }
bool JSCCharacter_set_tempstr( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 92 ); }
bool JSCCharacter_get_poison( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 93 ); }
bool JSCCharacter_set_poison( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 93 ); }
bool JSCCharacter_get_poisonedBy( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 94 ); }
bool JSCCharacter_set_poisonedBy( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 94 ); }
bool JSCCharacter_get_lightlevel( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 95 ); }
bool JSCCharacter_set_lightlevel( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 95 ); }
bool JSCCharacter_get_vulnerable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 96 ); }
bool JSCCharacter_set_vulnerable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 96 ); }
bool JSCCharacter_get_willhunger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 97 ); }
bool JSCCharacter_set_willhunger( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 97 ); }
bool JSCCharacter_get_willthirst( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 98 ); }
bool JSCCharacter_set_willthirst( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 98 ); }
bool JSCCharacter_get_lodamage( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 99 ); }
bool JSCCharacter_set_lodamage( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 99 ); }
bool JSCCharacter_get_hidamage( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 100 ); }
bool JSCCharacter_set_hidamage( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 100 ); }
bool JSCCharacter_get_flag( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 101 ); }
bool JSCCharacter_get_atWar( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 102 ); }
bool JSCCharacter_set_atWar( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 102 ); }
bool JSCCharacter_get_spellCast( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 103 ); }
bool JSCCharacter_set_spellCast( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 103 ); }
bool JSCCharacter_get_isCasting( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 104 ); }
bool JSCCharacter_set_isCasting( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 104 ); }
bool JSCCharacter_get_priv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 105 ); }
bool JSCCharacter_set_priv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 105 ); }
bool JSCCharacter_get_townPriv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 106 ); }
bool JSCCharacter_set_townPriv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 106 ); }
bool JSCCharacter_get_guildTitle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 107 ); }
bool JSCCharacter_set_guildTitle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 107 ); }
bool JSCCharacter_get_hairStyle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 108 ); }
bool JSCCharacter_set_hairStyle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 108 ); }
bool JSCCharacter_get_hairColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 109 ); }
bool JSCCharacter_set_hairColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 109 ); }
bool JSCCharacter_get_hairColor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 109 ); }
bool JSCCharacter_set_hairColor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 109 ); }
bool JSCCharacter_get_beardStyle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 110 ); }
bool JSCCharacter_set_beardStyle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 110 ); }
bool JSCCharacter_get_beardColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 111 ); }
bool JSCCharacter_set_beardColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 111 ); }
bool JSCCharacter_get_beardColor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 111 ); }
bool JSCCharacter_set_beardColor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 111 ); }
bool JSCCharacter_get_fontType( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 112 ); }
bool JSCCharacter_set_fontType( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 112 ); }
bool JSCCharacter_get_sayColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 113 ); }
bool JSCCharacter_set_sayColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 113 ); }
bool JSCCharacter_get_emoteColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 114 ); }
bool JSCCharacter_set_emoteColour( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 114 ); }
bool JSCCharacter_get_attacker( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 115 ); }
bool JSCCharacter_set_attacker( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 115 ); }
bool JSCCharacter_get_raceGate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 116 ); }
bool JSCCharacter_set_raceGate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 116 ); }
bool JSCCharacter_get_skillLock( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 117 ); }
bool JSCCharacter_set_skillLock( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 117 ); }
bool JSCCharacter_get_skillCaps( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 118 ); }
bool JSCCharacter_set_skillCaps( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 118 ); }
bool JSCCharacter_get_deaths( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 119 ); }
bool JSCCharacter_set_deaths( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 119 ); }
bool JSCCharacter_get_ownerCount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 120 ); }
bool JSCCharacter_set_ownerCount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 120 ); }
bool JSCCharacter_get_nextAct( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 121 ); }
bool JSCCharacter_set_nextAct( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 121 ); }
bool JSCCharacter_get_petCount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 122 ); }
bool JSCCharacter_get_followerCount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 123 ); }
bool JSCCharacter_get_ownedItemsCount( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 124 ); }
bool JSCCharacter_get_cell( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 125 ); }
bool JSCCharacter_set_cell( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 125 ); }
bool JSCCharacter_get_allmove( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 126 ); }
bool JSCCharacter_set_allmove( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 126 ); }
bool JSCCharacter_get_houseicons( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 127 ); }
bool JSCCharacter_set_houseicons( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 127 ); }
bool JSCCharacter_get_spattack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 130 ); }
bool JSCCharacter_set_spattack( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 130 ); }
bool JSCCharacter_get_spdelay( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 131 ); }
bool JSCCharacter_set_spdelay( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 131 ); }
bool JSCCharacter_get_swingSpeedIncrease( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 132 ); }
bool JSCCharacter_set_swingSpeedIncrease( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 132 ); }
bool JSCCharacter_get_luck( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 133 ); }
bool JSCCharacter_set_luck( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 133 ); }
bool JSCCharacter_get_damageIncrease( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 134 ); }
bool JSCCharacter_set_damageIncrease( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 134 ); }
bool JSCCharacter_get_hitChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 135 ); }
bool JSCCharacter_set_hitChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 135 ); }
bool JSCCharacter_get_defenseChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 136 ); }
bool JSCCharacter_set_defenseChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 136 ); }
bool JSCCharacter_get_aitype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 137 ); }
bool JSCCharacter_set_aitype( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 137 ); }
bool JSCCharacter_get_split( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 138 ); }
bool JSCCharacter_set_split( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 138 ); }
bool JSCCharacter_get_splitchance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 139 ); }
bool JSCCharacter_set_splitchance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 139 ); }
bool JSCCharacter_get_hireling( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 142 ); }
bool JSCCharacter_set_hireling( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 142 ); }
bool JSCCharacter_get_trainer( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 141 ); }
bool JSCCharacter_set_trainer( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 141 ); }
bool JSCCharacter_get_weight( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 143 ); }
bool JSCCharacter_set_weight( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 143 ); }
bool JSCCharacter_get_squelch( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 144 ); }
bool JSCCharacter_set_squelch( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 144 ); }
bool JSCCharacter_get_isJailed( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 145 ); }
bool JSCCharacter_get_magicReflect( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 146 ); }
bool JSCCharacter_set_magicReflect( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 146 ); }
bool JSCCharacter_get_permanentMagicReflect( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 147 ); }
bool JSCCharacter_set_permanentMagicReflect( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 147 ); }
bool JSCCharacter_get_hideFameKarmaTitle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 148 ); }
bool JSCCharacter_set_hideFameKarmaTitle( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 148 ); }
bool JSCCharacter_get_noCharCollide( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 149 ); }
bool JSCCharacter_set_noCharCollide( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 149 ); }
bool JSCCharacter_get_tamed( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 150 ); }
bool JSCCharacter_set_tamed( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 150 ); }
bool JSCCharacter_get_tamedHungerRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 151 ); }
bool JSCCharacter_set_tamedHungerRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 151 ); }
bool JSCCharacter_get_tamedThirstRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 152 ); }
bool JSCCharacter_set_tamedThirstRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 152 ); }
bool JSCCharacter_get_hungerWildChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 153 ); }
bool JSCCharacter_set_hungerWildChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 153 ); }
bool JSCCharacter_get_thirstWildChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 154 ); }
bool JSCCharacter_set_thirstWildChance( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 154 ); }
bool JSCCharacter_get_foodList( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 155 ); }
bool JSCCharacter_set_foodList( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 155 ); }
bool JSCCharacter_get_mounted( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 156 ); }
bool JSCCharacter_set_mounted( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 156 ); }
bool JSCCharacter_get_stabled( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 157 ); }
bool JSCCharacter_set_stabled( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 157 ); }
bool JSCCharacter_get_isUsingPotion( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 158 ); }
bool JSCCharacter_set_isUsingPotion( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 158 ); }
bool JSCCharacter_get_stealth( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 159 ); }
bool JSCCharacter_set_stealth( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 159 ); }
bool JSCCharacter_get_skillToTame( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 160 ); }
bool JSCCharacter_set_skillToTame( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 160 ); }
bool JSCCharacter_get_skillToProv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 161 ); }
bool JSCCharacter_set_skillToProv( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 161 ); }
bool JSCCharacter_get_skillToPeace( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 162 ); }
bool JSCCharacter_set_skillToPeace( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 162 ); }
bool JSCCharacter_get_poisonStrength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 163 ); }
bool JSCCharacter_set_poisonStrength( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 163 ); }
bool JSCCharacter_get_isPolymorphed( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 164 ); }
bool JSCCharacter_set_isPolymorphed( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 164 ); }
bool JSCCharacter_get_isIncognito( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 165 ); }
bool JSCCharacter_set_isIncognito( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 165 ); }
bool JSCCharacter_get_isDisguised( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 166 ); }
bool JSCCharacter_set_isDisguised( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 166 ); }
bool JSCCharacter_get_canRun( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 167 ); }
bool JSCCharacter_set_canRun( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 167 ); }
bool JSCCharacter_get_isMeditating( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 170 ); }
bool JSCCharacter_set_isMeditating( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 170 ); }
bool JSCCharacter_get_isGM( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 171 ); }
bool JSCCharacter_set_isGM( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 171 ); }
bool JSCCharacter_get_canBroadcast( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 173 ); }
bool JSCCharacter_set_canBroadcast( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 173 ); }
bool JSCCharacter_get_singClickSer( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 174 ); }
bool JSCCharacter_set_singClickSer( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 174 ); }
bool JSCCharacter_get_noSkillTitles( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 175 ); }
bool JSCCharacter_set_noSkillTitles( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 175 ); }
bool JSCCharacter_get_isGMPageable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 176 ); }
bool JSCCharacter_set_isGMPageable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 176 ); }
bool JSCCharacter_get_canSnoop( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 177 ); }
bool JSCCharacter_set_canSnoop( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 177 ); }
bool JSCCharacter_get_isCounselor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 178 ); }
bool JSCCharacter_set_isCounselor( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 178 ); }
bool JSCCharacter_get_noNeedMana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 179 ); }
bool JSCCharacter_set_noNeedMana( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 179 ); }
bool JSCCharacter_get_isDispellable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 180 ); }
bool JSCCharacter_set_isDispellable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 180 ); }
bool JSCCharacter_get_noNeedReags( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 181 ); }
bool JSCCharacter_set_noNeedReags( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 181 ); }
bool JSCCharacter_get_orgID( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 182 ); }
bool JSCCharacter_set_orgID( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 182 ); }
bool JSCCharacter_get_orgSkin( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 183 ); }
bool JSCCharacter_set_orgSkin( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 183 ); }
bool JSCCharacter_get_isAnimal( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 186 ); }
bool JSCCharacter_get_isPackAnimal( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 187 ); }
bool JSCCharacter_get_isHuman( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 188 ); }
bool JSCCharacter_get_isShop( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 190 ); }
bool JSCCharacter_set_isShop( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 190 ); }
bool JSCCharacter_get_maxLoyalty( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 191 ); }
bool JSCCharacter_set_maxLoyalty( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 191 ); }
bool JSCCharacter_get_loyalty( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 192 ); }
bool JSCCharacter_set_loyalty( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 192 ); }
bool JSCCharacter_get_loyaltyRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 193 ); }
bool JSCCharacter_set_loyaltyRate( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 193 ); }
bool JSCCharacter_get_shouldSave( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 194 ); }
bool JSCCharacter_set_shouldSave( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 194 ); }
bool JSCCharacter_get_origin( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 195 ); }
bool JSCCharacter_set_origin( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 195 ); }
bool JSCCharacter_get_partyLootable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 196 ); }
bool JSCCharacter_set_partyLootable( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 196 ); }
bool JSCCharacter_get_party( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 197 ); }
bool JSCCharacter_get_multi( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 198 ); }
bool JSCCharacter_set_multi( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 198 ); }
bool JSCCharacter_get_accountNum( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 199 ); }
bool JSCCharacter_set_accountNum( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 199 ); }
bool JSCCharacter_get_account( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 200 ); }
bool JSCCharacter_set_account( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 200 ); }
bool JSCCharacter_get_createdOn( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 201 ); }
bool JSCCharacter_set_createdOn( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 201 ); }
bool JSCCharacter_get_playTime( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 202 ); }
bool JSCCharacter_set_playTime( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 202 ); }
bool JSCCharacter_get_housesOwned( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 203 ); }
bool JSCCharacter_set_housesOwned( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 203 ); }
bool JSCCharacter_get_housesCoOwned( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 204 ); }
bool JSCCharacter_set_housesCoOwned( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 204 ); }
bool JSCCharacter_get_tithing( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 172 ); }
bool JSCCharacter_set_tithing( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacySet( cx, argc, vp, CCharacterProps_setProperty, 172 ); }
bool JSCCharacter_get_lastOn( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 206 ); }
bool JSCCharacter_get_lastOnSecs( JSContext *cx, unsigned argc, JS::Value *vp ) { return LegacyGet( cx, argc, vp, CCharacterProps_getProperty, 207 ); }
