name: Post UOX3 Release Candidate to Discord

on:
  release:
    types:
      - created

jobs:
  github-releases-to-discord:
    if: github.event.release.draft == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Post GitHub Release Candidates to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "15277667"
          username: "RC Changelog"
          avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
          max_description: 2000