name: Post UOX3 Release to Discord

on:
  release:
    types:
      - published

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "UOX3 Release Bot"
          avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
          content: "**A new UOX3 version has been released! [Click here to download.](${{ github.event.release.html_url }})**"
          max_description: 2000